// This file is part of bearssl-sys. It is subject to the license terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/bearssl-sys/master/COPYRIGHT. No part of bearssl-sys, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
// Copyright © 2016 The developers of bearssl-sys. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/bearssl-sys/master/COPYRIGHT.


#[repr(C)]
pub struct br_x509_minimal_context
{
	pub vtable: *const br_x509_class,
	pub pkey: br_x509_pkey,
	pub cpu: br_x509_minimal_context__bindgen_ty_1,
	pub dp_stack: [u32; 32usize],
	pub rp_stack: [u32; 32usize],
	pub err: c_int,
	pub server_name: *const c_char,
	pub key_usages: c_uchar,
	pub days: u32,
	pub seconds: u32,
	pub cert_length: u32,
	pub num_certs: u32,
	pub hbuf: *const c_uchar,
	pub hlen: usize,
	pub pad: [c_uchar; 256usize],
	pub ee_pkey_data: [c_uchar; 520usize],
	pub pkey_data: [c_uchar; 520usize],
	pub cert_signer_key_type: c_uchar,
	pub cert_sig_hash_oid: u16,
	pub cert_sig_hash_len: c_uchar,
	pub cert_sig: [c_uchar; 512usize],
	pub cert_sig_len: u16,
	pub min_rsa_size: i16,
	pub trust_anchors: *const br_x509_trust_anchor,
	pub trust_anchors_num: usize,
	pub do_mhash: c_uchar,
	pub mhash: br_multihash_context,
	pub tbs_hash: [c_uchar; 64usize],
	pub do_dn_hash: c_uchar,
	pub dn_hash_impl: *const br_hash_class,
	pub dn_hash: br_hash_compat_context,
	pub current_dn_hash: [c_uchar; 64usize],
	pub next_dn_hash: [c_uchar; 64usize],
	pub saved_dn_hash: [c_uchar; 64usize],
	pub name_elts: *mut br_name_element,
	pub num_name_elts: usize,
	pub irsa: br_rsa_pkcs1_vrfy,
	pub iecdsa: br_ecdsa_vrfy,
	pub iec: *const br_ec_impl,
}
